apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotion-detector-deployment
  labels:
    app: emotion-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotion-detector
  template:
    metadata:
      labels:
        app: emotion-detector
    spec:
      containers:
      - name: emotion-detector-container
        image: siralex01/emotion-detector:latest
        ports:
        - containerPort: 5050
        env:
        - name: FLASK_ENV
          value: production
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: access_key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: secret_key
        - name: MODEL_BUCKET
          valueFrom:
            configMapKeyRef:
              name: minio-model-config
              key: MODEL_BUCKET
        - name: MODEL_NAME
          valueFrom:
            configMapKeyRef:
              name: minio-model-config
              key: MODEL_NAME
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
