apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list", "watch"]
