apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: emofy-db-container-claim0
  name: emofy-db-container-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
