apiVersion: v1
kind: Service
metadata:
  name: image-filters-service
spec:
  selector:
    app: image-filters
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
