apiVersion: v1
kind: Service
metadata:
  name: emofy-image-storage
spec:
  selector:
    app: emofy-image-storage
  type: LoadBalancer 
  ports:
    - name: "http"
      port: 8081
      targetPort: 8080
