apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000   # Porta API di MinIO
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001  # Porta dell'interfaccia utente web di MinIO
  type: LoadBalancer
