apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Pc\Desktop\MECELLONE\EMOFY\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: emofy-login-service
  name: emofy-login-service
spec:
  type: LoadBalancer  # Utilizzo del tipo di servizio LoadBalancer per rendere il servizio accessibile dall'esterno
  ports:
      port: 8085
      targetPort: 8080
  selector:
    io.kompose.service: emofy-login-service
