version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "xpack.security.enabled=false"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.http.ssl.enabled=false"
      - "ELASTIC_PASSWORD=elastic123" 
      - "KIBANA_SYSTEM_PASSWORD=kibana123"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana123 
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.1
    container_name: logstash
    command: logstash -f /logstash_dir/logstash.conf #command at startup to setup configuration file
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - ./logstash/:/logstash_dir
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elastic_data: {}

networks:
  elk:
    driver: bridge

