apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      name: elastic9200
    - port: 9300
      targetPort: 9300
      name: elastic9300
  selector:
    app: elasticsearch
