apiVersion: apps/v1
kind: Deployment
metadata:
  name: emofy-image-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emofy-image-storage
  template:
    metadata:
      labels:
        app: emofy-image-storage
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z minio-service 9000; do sleep 2; done;']

      containers:
      - name: emofy-image-storage
        image: siralex01/emofy-image-storage:latest
        ports:
        - containerPort: 8080
        # Immagine Docker del tuo microservizio
