apiVersion: apps/v1
kind: Deployment
metadata:
  name: emofy-db-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emofy-db-container
  template:
    metadata:
      labels:
        app: emofy-db-container
    spec:
      containers:
      - name: emofy-db-container
        image: postgres:13.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: emofy_db

