apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Pc\Desktop\MECELLONE\EMOFY\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: emofy-db-container
  name: emofy-db-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emofy-db-container
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Pc\Desktop\MECELLONE\EMOFY\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/emofy-default: "true"
        io.kompose.service: emofy-db-container
    spec:
      initContainers:
        - name: download-init-script
          image: alpine
          command: ["wget", "-O", "/docker-entrypoint-initdb.d/init.sql", "https://raw.githubusercontent.com/kev187038/EMOFY/master/login/emofy_db.sql"]
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: emofy-db-container-claim0
      containers:
        - env:
            - name: POSTGRES_DB
              value: emofy_db
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: postgres:13.1-alpine
          name: emofy-db-container
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: emofy-db-container-claim0
      restartPolicy: Always
      volumes:
        - name: emofy-db-container-claim0
          persistentVolumeClaim:
            claimName: emofy-db-container-claim0
