apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Pc\Desktop\MECELLONE\EMOFY\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: emofy-login-service
  name: emofy-login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: emofy-login-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Pc\Desktop\MECELLONE\EMOFY\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/emofy-default: "true"
        io.kompose.service: emofy-login-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z emofy-db-container 5432; do sleep 2; done;']
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://emofy-db-container:5432/emofy_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: siralex01/docker-spring-boot-postgres:latest #Cambiata questa prima era 
          imagePullPolicy: IfNotPresent
          name: emofy-login-service
          ports:
            - containerPort: 8080
              hostPort: 8085
              protocol: TCP
      restartPolicy: Always
