apiVersion: batch/v1
kind: CronJob
metadata:
  name: emofy-retraining
spec:
  schedule: "0 0 1 * *"  # This means the job will run at midnight on the first day of every month
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600  # Delete the job 1 hour after completion
      template:
        spec:
          containers:
            - name: emofy-retraining
              image: placidop/emofy-retraining:latest
              env:
                - name: LOGIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: login-credentials
                      key: username
                - name: LOGIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: login-credentials
                      key: password
                - name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: access_key
                - name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-credentials
                      key: secret_key
                - name: MODEL_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: minio-model-config
                      key: MODEL_BUCKET
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "1"
                  nvidia.com/gpu: 1 # Request 1 GPU
                limits:
                  memory: "4Gi"
                  cpu: "2"
                  nvidia.com/gpu: 1 # Limit to 1 GPU
          restartPolicy: Never
