apiVersion: v1
kind: Service
metadata:
  name: emotion-detector-service
spec:
  selector:
    app: emotion-detector
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
